### ISSUE TITLE
🐛 Players who don't have op can access bo commands

### ISSUE THREAD

**Issue by ApoWillow** [ejektaflex/Bountiful-Fabric#23] opened 2022-02-16 21:07 UTC
Players who don't have op can access the bo commands to get decrees and missions without a timer (im not sure if this is a glitch but if it isn't this is a suggestion to make it so that only oped players can acces the bo commands)

**Comment by ejektaflex** [comment] 2022-02-16 22:03
Noted! Duplicate of #19

**Closed as completed by ejektaflex** 2022-02-16 22:03 UTC
