### ISSUE TITLE
Missing Texture Error in Logs

### ISSUE THREAD

**Issue by greensad** [ejektaflex/Bountiful-Fabric#24] opened 2022-02-19 22:40 UTC
Using missing texture, unable to load bountiful:textures/item/decree.png : java.io.FileNotFoundException: bountiful:textures/item/decree.png

https://paste.ee/p/0ZBus

**Comment by ejektaflex** [comment] 2022-02-24 22:21
Duplicate of ejektaflex/Bountiful#211

**Closed as completed by ejektaflex** 2022-02-24 22:21 UTC
