### ISSUE TITLE
Error with latest version of fabric mod

### ISSUE THREAD

**Issue by AngelosNaoumis** [ejektaflex/Bountiful-Fabric#33] opened 2022-08-29 13:48 UTC
[16:44:54] [main/ERROR]: Couldn't parse loot table bountiful:blocks/bountyboard
com.google.gson.JsonSyntaxException: Missing type, expected to find a string
        at net.minecraft.class_3518.method_15265(class_3518.java:119) ~[server-intermediary.jar:?]
        at net.minecraft.class_134$class_136.method_605(class_134.java:112) ~[server-intermediary.jar:?]
        at net.minecraft.class_134$class_136.method_530(class_134.java:101) ~[server-intermediary.jar:?]
        at net.minecraft.class_120$class_123.method_528(class_120.java:99) ~[server-intermediary.jar:?]
        at net.minecraft.class_120$class_123.method_517(class_120.java:88) ~[server-intermediary.jar:?]
        at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
        at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[server-intermediary.jar:?]
        at net.minecraft.class_3518.method_15283(class_3518.java:473) ~[server-intermediary.jar:?]
        at net.minecraft.class_85$class_90.method_441(class_85.java:149) ~[server-intermediary.jar:?]
        at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[server-intermediary.jar:?]
        at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
        at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
        at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[server-intermediary.jar:?]
        at net.minecraft.class_3518.method_15272(class_3518.java:463) ~[server-intermediary.jar:?]
        at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
        at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[server-intermediary.jar:?]
        at net.minecraft.class_3518.method_15283(class_3518.java:473) ~[server-intermediary.jar:?]
        at net.minecraft.class_52$class_54.method_340(class_52.java:214) ~[server-intermediary.jar:?]
        at net.minecraft.class_52$class_54.deserialize(class_52.java:210) ~[server-intermediary.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
        at net.minecraft.class_60.method_20711(class_60.java:44) ~[server-intermediary.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at net.minecraft.class_60.method_20712(class_60.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:958) [server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:946) [server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:156) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]

**Comment by ejektaflex** [comment] 2022-08-30 05:12
Closed as duplicate of ejektaflex/Bountiful#211

**Closed as completed by ejektaflex** 2022-08-30 05:12 UTC
