### ISSUE TITLE
JsonSyntaxException

### ISSUE THREAD

**Issue by imcasper** [ejektaflex/Bountiful-Fabric#22] opened 2022-02-02 20:16 UTC
**java-17
game-version 1.18.1
fabric-api-0.46.1+1.18.jar
mod: 2.0.2 (or 2.0.1, because console write 2.0.1, but file name "...2.0.2")**

console output (launch server):

[23:12:34] [Worker-Main-7/INFO]: Loaded 31 recipes
[23:12:34] [Worker-Main-7/ERROR]: Couldn't parse loot table bountiful:blocks/bountyboard
com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at net.minecraft.class_3518.method_15265(class_3518.java:112) ~[server-intermediary.jar:?]
	at net.minecraft.class_134$class_136.method_605(class_134.java:112) ~[server-intermediary.jar:?]
	at net.minecraft.class_134$class_136.method_530(class_134.java:101) ~[server-intermediary.jar:?]
	at net.minecraft.class_120$class_123.method_528(class_120.java:99) ~[server-intermediary.jar:?]
	at net.minecraft.class_120$class_123.method_517(class_120.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_441(class_85.java:149) ~[server-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:456) ~[server-intermediary.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[server-intermediary.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[server-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar:?]
	at net.minecraft.class_60.method_20711(class_60.java:44) ~[server-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_60.method_20712(class_60.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**PS Also i not sure is it bug or not:**
[23:12:38] [Server thread/INFO]: [STDOUT]: LENIENT STACK SIZE: Starting starting. Loading config.
[23:12:38] [Server thread/INFO]: [STDOUT]: Found entry at 0. It is called "minecraft:saddle" and has a max stack of com.astrazoey.lenientstacksize.ItemStackConfig@1489fdf3.
[23:12:38] [Server thread/INFO]: [STDOUT]: Found entry at 1. It is called "minecraft:diamond_horse_armor" and has a max stack of com.astrazoey.lenientstacksize.ItemStackConfig@7f4d1f9b.
....
May be expected some integer in line end...

**Comment by ejektaflex** [comment] 2022-02-03 16:40
Duplicate of ejektaflex/Bountiful#211

**Closed as completed by ejektaflex** 2022-02-03 16:40 UTC
